# Generated by Django 5.1 on 2024-08-15 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaivariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='chaiFolder/')),
                ('chaiTypes', models.CharField(choices=[('DP', 'DoodhPatti'), ('ST', 'StrongChai'), ('GC', 'GingerChai'), ('EL', 'ElachiChai')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
